### ISSUE TITLE
Alertmanager can't use its data mount when using persistent volume

### ISSUE THREAD

**Issue by marekm-gain** [astronomer/astronomer#1043]
When using data mount with values like below:
```yaml
    dataDir: "/data"
    persistence:
      enabled: true
      size: 2Gi
      storageClassName: longhorn
```
this dir is only accessible to root however alertmanager is running as nobody(65534). Therefore is not able to access it.
