### ISSUE TITLE
auth sidecar enhancements

### ISSUE THREAD

**Issue by pgvishnuram** [astronomer/astronomer#1130]
* add health check endpoint for sidecar services
* sync passing data from houston to airflow chart
* change sidecar naming convention from nginx to auth-proxy
* follow same image definition pattern for authsidecar
```yaml
  authSidecar:
    repository: 
    tag: stable
    pullPolicy: IfNotPresent
```
