### ISSUE TITLE
Kibana content-security-policy page errors

### ISSUE THREAD

**Issue by alexbegg** [astronomer/astronomer#1275]
The Kibana that comes with Astronomer (I am on Astronomer platform v0.25.11) shows an error "Your browser does not meet the security requirements for Kibana."

![Screen Shot 2021-11-11 at 4 53 56 PM](https://user-images.githubusercontent.com/45696489/141390213-87fb1b62-cf15-42eb-8d73-66034652dd0b.png)

When I looked up this message online and it appears to be related to `content-security-policy`: https://discuss.elastic.co/t/browser-security-requirements-warning-when-login/241257

I checked the console messages and it is bringing up a few `content-security-policy` page errors, primarily for the following two URLs:

- `https://feeds.elastic.co/kibana/v7.10.2.json`
- `https://telemetry.elastic.co/xpack/v2/send`

Should the `Content-Security-Policy` be updated for NGINX here?
https://github.com/astronomer/astronomer/blob/88af33958326a9e955e2c5b25f280c9b42a2f68b/charts/nginx/templates/nginx-headers-configmap.yaml#L15

**Comment by pgvishnuram** [comment]
@danielhoherd

**Comment by danielhoherd** [comment]
Internal discussion thread: <https://astronomer.slack.com/archives/CE3J4L7QT/p1642632753017900>

**Comment by alexbegg** [comment]
@pgvishnuram @danielhoherd Any update on this?

I can't see that link since I am a not a Astronomer employee, I am an enterprise customer.

FYI, I wanted to state I added a few Kibana configurations via environment variables via Helm values to get rid of any errors or warnings:
```
kibana:
  env:
    SERVER_PUBLICBASEURL: "https://kibana.<BASEDOMAIN_HERE>" # There is currently a warning on Kibana pages stating that `server.publicBaseUrl` is missing and should be configured, so setting it here.
    CSP_WARNLEGACYBROWSERS: "false" # There is currently a warning on Kibana pages "Your browser does not meet the security requirements for Kibana.", disabling the warning for now.
    NEWSFEED_ENABLED: "false" # There is currently a Content Security Policy restriction connecting to the news feed, disabling it for now.
```

The last one, `NEWSFEED_ENABLED: "false"` avoids the Content Security Policy restriction connecting to `https://feeds.elastic.co/kibana/v`...`.json` since that request is to the news feed.

It seems the error with `https://telemetry.elastic.co/xpack/v2/send` went away in a recent release.
