### ISSUE TITLE
Grafana configurations are not easily customizable

### ISSUE THREAD

**Issue by dintorf** [astronomer/astronomer#1308]
Currently I see no way to customize the `grafana.ini` in the helm chart. This makes it difficult to configure any settings for the grafana deployment (i.e. smtp settings for alerting, see [Ticket #7151](https://astronomer.zendesk.com/agent/tickets/7151)). 

A possible solution is to allow extra environment variables to be passed to the grafana configuration in the Astronomer helm chart values. For example:

```yaml
grafana:
  extraEnvVars: 
    - name: GF_SMTP_ENABLED
       value: true
    - name: GF_SMTP_HOST
       value: smtp.astronomer.io
    - name: GF_SMTP_USER
       value: grafana
    - name: GF_SMTP_PASSWORD
       valueFrom:
          secretKeyRef:
            name: grafana-smtp-secret
            key: smtp_password
```

This would allow you to populate those env vars into the deployment template and modify configurations for Grafana. I'd be willing to contribute this change if this is accepted.
