### ISSUE TITLE
Stan and Nats do not allow nodeSelector, tolerations, or affinity configuration

### ISSUE THREAD

**Issue by dintorf** [astronomer/astronomer#1346]
All charts except for `stan` and `nats` are configured to allow changing the `nodeSelector`, `tolerations`, and `affinity`. This is a useful configuration for users who want to limit the specific nodes for all Astronomer pods. 

Suggested fix:

add to values.yaml for both charts:
```yaml
nodeSelector: {}
tolerations: []
affinity: {}
```

add to statefulset.yaml:
```yaml
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
```
