### ISSUE TITLE
Add ability to provide individual subdomain tls cert

### ISSUE THREAD

**Issue by whyvez** [astronomer/astronomer#1369]
We use google manager certificates and they do not support wildcard certificates. Could you expand your values to support passing in tls secret values for each subdomain?

```yaml
tlsSecrets:
  app: astronomer-tls-app
  deployments: astronomer-tls-deployments
  ...
```

Alternatively, you could have a `tlsSecretPrefix` and imply cert secret based on the subdomain.

```yaml
tlsSecretPrefix: astronomer-tls
```
