### ISSUE TITLE
Expose Helm chart probes in a way that allows the user to only explicitly override the values they need

### ISSUE THREAD

**Issue by nsAstro** [astronomer/astronomer#2451]
PR #2300 changed the fundamental behavior of how our chart operates when it comes to overriding specific liveness probes. Specifically, by changing how we template a probe, any user attempting to override a single probe attribute must respecify the entire probe.

```
          {{- if .Values.astroUI.livenessProbe }}
          livenessProbe: {{ tpl (toYaml .Values.astroUI.livenessProbe) . | nindent 12 }}
          {{- else}}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.astroUIHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
```

In the above block, if values.yaml specifies a livenessProbe, then every attribute of the new override probe must be specified instead of just being able to override .Values.astroUI.livenessProbe.periodSeconds=30

This also breaks backwards compatibility for parts of the chart where we used to expose each underlying value and have switched to the new model of block-replacing the probe. Helm has a better pattern for this in general by using the [merge](https://helm.sh/docs/chart_template_guide/function_list/#merge-mustmerge) function. Using this plus a helper partial template would allow the use of a defaultProbe setting that can then be overridden for specific probes.
