### ISSUE TITLE
resource quota deadlock issue during replicaset roll out

### ISSUE THREAD

**Issue by Saggi432** [astronomer/astronomer#764]
we recently found this issue when rolling out the updates to scheduler and worker. 

### Observed Versions

Astronomer v0.10.2

### Expected Behaviour

The rollout should happen without any issues with regards to the memory or cpu with the existing quota.

### Actual Behaviour

The existing resource quota is as below.

```         spec:
            hard:
              limits.cpu: "11"
              limits.ephemeral-storage: 50Gi
              limits.memory: 42240Mi
              pods: "16"
              requests.cpu: "11"
              requests.ephemeral-storage: 50Gi
              requests.memory: 42240Mi
          status:
            hard:
              limits.cpu: "11"
              limits.ephemeral-storage: 50Gi
              limits.memory: 42240Mi
              pods: "16"
              requests.cpu: "11"
              requests.ephemeral-storage: 50Gi
              requests.memory: 42240Mi
            used:
              limits.cpu: 10300m
              limits.ephemeral-storage: 10Gi
              limits.memory: 39552Mi
              pods: "8"
              requests.cpu: 10300m
              requests.ephemeral-storage: 4Gi
              requests.memory: 39552Mi 

```

Now if we try to roll out a new replicaset, our deployment for scheduler and  worker fails with the below warning and does not apply the new changes. Although there is no impact of pods being crashed out, but the new updates are not applied anymore.

This is not seen as a deployment failure in the UI on astronomer but the scheduler does not have the new updates which just got pushed.

```4m48s       Warning   FailedCreate        replicaset/zodiacal-space-9814-worker-c54cdc56b       Error creating: pods "zodiacal-space-9814-worker-c54cdc56b-p9sf6" is forbidden: exceeded quota: zodiacal-space-9814-resource-quota, requested: limits.memory=5760Mi,requests.memory=5760Mi, used: limits.memory=49536Mi,requests.memory=49536Mi, limited: limits.memory=52240Mi,requests.memory=52240Mi ```

### Steps to reproduce Behaviour

In our case we saw this issue when we tried to change the cpu and mem configs for scheduler as below

Old Config

```
        name: scheduler
        resources:
          limits:
            cpu: 1100m
            ephemeral-storage: 4Gi
            memory: 4224Mi
          requests:
            cpu: 1100m
            ephemeral-storage: 1Gi
            memory: 4224Mi
```

New Config
```
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 4Gi
            memory: 3840Mi
          requests:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 3840Mi
```

### Possible Reasons 

I feel that its because of the rolling update strategy, it cannot kill the pod thats running unless it brings up the new one. However it cannot bring the new one because the resource quota restricts the creation of the new pod as we are already under the limit.

I guess it would make sense to create the resource quota once the pods are successfully deployed.
